### ISSUE TITLE
ReferenceError: verbose is not defined

### ISSUE THREAD

**Issue by gnimmelf** [cyclejs-community/one-fits-all#38]
`create-cycle-app cycle-app.2 --flavor cycle-scripts-one-fits-all --verbose`

```
/workspace/cycle-app.2/node_modules/cycle-scripts-one-fits-all/scripts/init.js:84
    const verbose = isObj ? verboseOpts.verbose : verbose;
                                                  ^

ReferenceError: verbose is not defined
    at init (/home/gnimmelf/workspace/cycle-app.2/node_modules/cycle-scripts-one-fits-all/scripts/init.js:84:51)
    at ChildProcess.<anonymous> (/home/gnimmelf/opt/node-v8.1.2-linux-x64/lib/node_modules/create-cycle-app/src/installScripts.js:48:5)
    at emitTwo (events.js:125:13)
    at ChildProcess.emit (events.js:213:7)
    at maybeClose (internal/child_process.js:897:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:208:5)
```

Thanks!

**Comment by jvanbruegge** [comment]
Sorry for your troubles, I fixed this issue in V4.2.2

**Comment by gnimmelf** [comment]
Oh, sorry, thought I had the last version. My bad.

**Comment by jvanbruegge** [comment]
You had. I just fixed it :)

**Comment by gnimmelf** [comment]
Weird, but good :)
