### ISSUE TITLE
Error with create-cycle-app my-app --flavor one-fits-all

### ISSUE THREAD

**Issue by baranovxyz** [cyclejs-community/one-fits-all#44]
Error leads to this log:
```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   'install',
1 verbose cli   '--save-dev',
1 verbose cli   '--save-exact',
1 verbose cli   'one-fits-all' ]
2 info using npm@5.4.2
3 info using node@v8.1.4
4 verbose npm-session e1068205c7b64365
5 silly install loadCurrentTree
6 silly install readLocalPackageData
7 http fetch GET 404 https://registry.npmjs.org/one-fits-all 1653ms
8 silly fetchPackageMetaData error for one-fits-all@latest 404 Not Found: one-fits-all@latest
9 verbose stack Error: 404 Not Found: one-fits-all@latest
9 verbose stack     at fetch.then.res (/usr/local/lib/node_modules/npm/node_modules/pacote/lib/fetchers/registry/fetch.js:42:19)
9 verbose stack     at tryCatcher (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/util.js:16:23)
9 verbose stack     at Promise._settlePromiseFromHandler (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:512:31)
9 verbose stack     at Promise._settlePromise (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:569:18)
9 verbose stack     at Promise._settlePromise0 (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:614:10)
9 verbose stack     at Promise._settlePromises (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:693:18)
9 verbose stack     at Async._drainQueue (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/async.js:133:16)
9 verbose stack     at Async._drainQueues (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/async.js:143:10)
9 verbose stack     at Immediate.Async.drainQueues (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/async.js:17:14)
9 verbose stack     at runCallback (timers.js:800:20)
9 verbose stack     at tryOnImmediate (timers.js:762:5)
9 verbose stack     at processImmediate [as _immediateCallback] (timers.js:733:5)
10 verbose cwd /Users/valery/Examples/my-app
11 verbose Darwin 16.7.0
12 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "--save-dev" "--save-exact" "one-fits-all"
13 verbose node v8.1.4
14 verbose npm  v5.4.2
15 error code E404
16 error 404 Not Found: one-fits-all@latest
17 verbose exit [ 1, true ]
```

**Comment by jvanbruegge** [comment]
The package name is `cycle-scripts-one-fits-all`
not `one-fits-all`

**Comment by jvanbruegge** [comment]
I will update the README to make it clearer
